version: '3.3'

services:
  app:
    container_name: chat
    build: ./app
    ports:
      - "8516:8516"
    volumes:
      - ./app:/app
    command: >
      sh -c "python3 manage.py makemigrations --noinput &&
             while ! python3 manage.py migrate --noinput ; do sleep 1 ; done && 
             python3 manage.py createsuperuser --user admin --noinput --email admin@admin.com --noinput ;
             python3 manage.py collectstatic --noinput;
             daphne -b 0.0.0.0 -p 8516 djangochannels.asgi:application"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=djangochannels.settings
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=postgresqlpassword

  db:
    container_name: db
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresqlpassword
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./app/staticfiles:/etc/nginx/chat/staticfiles
